version: '3.4'

services:
  cyber1cadastro:
    image: cyber1cadastro
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:80
